on: [push, pull_request]

jobs:
  build:
    name: Build all packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: |
          yarn
          yarn bootstrap

      - name: Build
        run: yarn build

      - name: Check bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn bundlesize

  test:
    name: Test all packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: |
          npm install -g yarn
          yarn
          yarn bootstrap

      - name: Jest
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          yarn test --coverage

      - name: Upload to codecov
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          yarn codecov
